version: "3.8"
services:
  invidious:
    image: quay.io/invidious/invidious:${TAG:-latest-arm64}
    restart: always
    stop_grace_period: 3s
    ports:
      - 127.0.0.1:${PORT:-81}:3000
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: invidious
          password: password
          host: postgres
          port: 5432
        check_tables: true
        popular_enabled: false
        login_enabled: false
        statistics_enabled: false
        hsts: false
        https_only: true
        domain: ${INSTANCE_ID}.watchtube.app
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    # purposefully excluded volumes section
    # the database will reset on recreate
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: invidious
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U invidious -d invidious
      interval: 10s
      timeout: 5s
      retries: 5
